### ISSUE TITLE
Error occurred while enabling NekoGuard v0.0.0

### ISSUE THREAD

**Issue by Bkm016** [neko-craft/NekoGuard#1]
```
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```
```
[21:09:35] [Server thread/INFO]: [NekoGuard] Enabling NekoGuard v0.0.0
[21:09:35] [Server thread/WARN]: [NekoGuard] We strongly recommend that you use PaperSpigot for better effects. Please visit here: https://papermc.io
[21:09:35] [Server thread/ERROR]: Error occurred while enabling NekoGuard v0.0.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server$Spigot.getSpigotConfig()Lorg/bukkit/configuration/file/YamlConfiguration;
        at cn.apisium.nekoguard.bukkit.Main.onEnable(Main.java:64) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488) ~[1.16.1.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402) ~[1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436) ~[1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808) ~[1.16.1.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[1.16.1.jar:git-Spigot-758abbe-2b00831]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

**Comment by ShirasawaSama** [comment]
Fixed
